name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir aplicación
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/contador/browser

      - name: Publicar
        uses: actions/deploy-pages@v4

